FROM  168447636/deepin20:tools
USER root
WORKDIR  /depstack
COPY ./sources.list  /etc/apt/sources.list
COPY  .  .
ENV controllerIP=10.121.100.101
ENV net2Name=ens10
ENV ctl_net3_IP=12.1.0.101
RUN echo 10.121.1.254 download.exam.com  >> /etc/hosts && apt update && apt -y upgrade && \
  apt install -y apt-utils  && \
  apt-get -d -y install neutron-server neutron-plugin-ml2 neutron-plugin-linuxbridge-agent neutron-l3-agent neutron-dhcp-agent neutron-metadata-agent python3-neutronclient && \
  ls -l  /var/cache/apt/archives/neutron*.deb && \
  DEBIAN_FRONTEND=noninteractive dpkg-preconfigure /var/cache/apt/archives/neutron-api_*.deb && \
  DEBIAN_FRONTEND=noninteractive dpkg-preconfigure /var/cache/apt/archives/neutron-common_*.deb && \
  DEBIAN_FRONTEND=noninteractive dpkg-preconfigure /var/cache/apt/archives/neutron-metadata-agent*.deb && \
  echo "\
neutron neutron/configure_api-endpoint seen true\n\
neutron neutron/nova_service_password password\n\
neutron neutron/nova_region string RegionOne\n\
neutron neutron/configure_rabbit seen true\n\
neutron neutron/nova_auth_url string http://$controllerIP:5000\n\
neutron neutron/configure_ksat seen true\n\
neutron neutron/configure_db seen true\n\
neutron neutron-metadata/metadata_secret password\n\
neutron neutron-metadata/nova_metadata_host string $controllerIP "  | debconf-set-selections && \
  TERM=xterm apt-get install neutron-server neutron-plugin-ml2 neutron-plugin-linuxbridge-agent neutron-l3-agent neutron-dhcp-agent neutron-metadata-agent python3-neutronclient -y && \
  mv /etc/neutron/neutron.conf /etc/neutron/neutron.conf.bak && \
  egrep -v "^#|^$" /etc/neutron/neutron.conf.bak > /etc/neutron/neutron.conf && \
  echo "[DEFAULT]\n\
state_path = /var/lib/neutron\n\
dhcp_agent_notification = True\n\
transport_url = rabbit://uosrabbitmq:rabbitmq@controller\n\
auth_strategy = keystone\n\
core_plugin = ml2\n\
service_plugins = router,metering,qos\n\
allow_overlapping_ips = True\n\
notify_nova_on_port_status_changes = True\n\
notify_nova_on_port_data_changes = True\n\
interface_driver = neutron.agent.linux.interface.BridgeInterfaceDriver\n\
[agent]\n\
root_helper = sudo neutron-rootwrap /etc/neutron/rootwrap.conf\n\
[database]\n\
connection = mysql+pymysql://uosneutron:neutron@controller/neutron\n\
[keystone_authtoken]\n\
password = neutron\n\
memcached_servers = controller:11211\n\
auth_url = http://controller:35357\n\
project_name = service\n\
project_domain_name = default\n\
username = neutron\n\
user_domain_name = default\n\
www_authenticate_uri = http://controller:5000\n\
region_name = RegionOne\n\
auth_type = password\n\
[nova]\n\
password = nova\n\
region_name = RegionOne\n\
auth_url = http://controller:35357\n\
auth_type = password\n\
project_domain_name = default\n\
project_name = service\n\
user_domain_name = default\n\
username = nova\n\
[oslo_concurrency]\n\
lock_path = /var/lock/neutron\n\
[oslo_policy]\n\
policy_file = /etc/neutron/policy.json " > /etc/neutron/neutron.conf && \
  chmod 640 /etc/neutron/neutron.conf && \
  chgrp neutron /etc/neutron/neutron.conf && \
  echo "\
[DEFAULT]\n\
ovs_use_veth = False\n\
interface_driver = neutron.agent.linux.interface.BridgeInterfaceDriver\n\
[agent]\n\
[ovs] " > /etc/neutron/l3_agent.ini && \
  echo "\
[DEFAULT]\n\
interface_driver = neutron.agent.linux.interface.BridgeInterfaceDriver\n\
enable_isolated_metadata = True\n\
dhcp_driver = neutron.agent.linux.dhcp.Dnsmasq " > /etc/neutron/dhcp_agent.ini && \
  echo "\
[DEFAULT]\n\
nova_metadata_host = $controllerIP\n\
metadata_proxy_shared_secret =  metadata\n\
nova_metadata_protocol = http\n\
metadata_workers = 4\n\
[cache]\n\
memcache_servers = controller:11211 " > /etc/neutron/metadata_agent.ini && \
  echo "\
[DEFAULT]\n\
[agent]\n\
[linux_bridge]\n\
physical_interface_mappings = external:$net2Name\n\
[network_log]\n\
[securitygroup]\n\
firewall_driver = iptables\n\
enable_security_group = true\n\
enable_ipset = true\n\
[vxlan]\n\
enable_vxlan = true\n\
l2_population = true\n\
local_ip = $ctl_net3_IP "  > /etc/neutron/plugins/ml2/linuxbridge_agent.ini && \
  echo "\
[DEFAULT]\n\
[l2pop]\n\
[ml2]\n\
type_drivers = flat,vxlan,vlan\n\
tenant_network_types = vxlan\n\
mechanism_drivers = linuxbridge,l2population\n\
extension_drivers = port_security,qos\n\
path_mtu = 1500\n\
[ml2_type_flat]\n\
flat_networks = external\n\
[ml2_type_geneve]\n\
[ml2_type_gre]\n\
[ml2_type_vlan]\n\
[ml2_type_vxlan]\n\
vni_ranges = 1:1000\n\
[securitygroup]\n\
enable_security_group = true\n\
enable_ipset = true " > /etc/neutron/plugins/ml2/ml2_conf.ini && \
  mv ./sysctl /usr/sbin/sysctl && \
  update-alternatives --set ebtables  /usr/sbin/ebtables-legacy && \
  rm -f ./Dockerfile.* && \
  ln -s /etc/neutron/plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini && \
  cat hosts >>/etc/hosts && \
  apt autoremove && \
  apt-get clean && \
  rm -rf /usr/share/man /usr/share/doc && \
  rm -rf /var/lib/apt/lists/* && \
  du -sh /* ; \
  du -sh /usr/*; \
  cat /etc/hosts
CMD ["/bin/bash","./start.sh"]
