FROM centos:latest

RUN RELEASE="release-1.12.1" && \
curl -L --remote-name-all https://storage.googleapis.com/kubernetes-release/release/${RELEASE}/bin/linux/amd64/{kubeadm,kubelet,kubectl}

CMD ["/usr/bin/bash"]

