FROM  168447636/deepin20:tools
USER root
WORKDIR  /depstack
COPY ./sources.list  /etc/apt/sources.list
COPY  .  .
ENV computeIP=10.121.100.102
ENV controllerIP=10.121.100.101
ENV virt_type=qemu
RUN echo 10.121.1.254 download.exam.com  >> /etc/hosts && apt update && apt -y upgrade && \
  export DEBIAN_FRONTEND=noninteractive && \
  TERM=xterm  apt install -y  nova-compute  && \
  mv /etc/nova/nova.conf /etc/nova/nova.conf.bak && \
  echo "[DEFAULT]\n\
[DEFAULT]\n\
vif_plugging_timeout = 0\n\
vif_plugging_is_fatal = False\n\
my_ip = $computeIP\n\
state_path = /var/lib/nova\n\
enabled_apis = osapi_compute,metadata\n\
log_dir = /var/log/nova\n\
transport_url = rabbit://uosrabbitmq:rabbitmq@controller\n\
use_neutron = True \n\
linuxnet_interface_driver = nova.network.linux_net.LinuxBridgeInterfaceDriver \n\
firewall_driver = nova.virt.firewall.NoopFirewallDriver \n\
vnc_enabled = false\n\
[neutron] \n\
auth_url = http://controller:35357 \n\
auth_type = password \n\
project_domain_name = default \n\
user_domain_name = default \n\
region_name = RegionOne \n\
project_name = service \n\
username = neutron \n\
password = neutron \n\
service_metadata_proxy = True \n\
metadata_proxy_shared_secret = metadata\n\
[api]\n\
auth_strategy = keystone\n\
[libvirt]\n\
virt_type = $virt_type\n\
# Glance connection info\n\
[glance]\n\
api_servers = http://controller:9292\n\
[oslo_concurrency]  \n\
lock_path = \$state_path/tmp\n\
# Keystone auth info\n\
[keystone_authtoken]\n\
www_authenticate_uri = http://controller:5000\n\
auth_url = http://controller:35357\n\
memcached_servers = controller:11211\n\
auth_type = password\n\
project_domain_name = default\n\
user_domain_name = default\n\
project_name = service\n\
username = nova\n\
password = nova\n\
[placement]\n\
auth_url = http://controller:35357\n\
os_region_name = RegionOne\n\
auth_type = password\n\
project_domain_name = default\n\
user_domain_name = default\n\
project_name = service\n\
username = placement\n\
password = placement\n\
[wsgi]\n\
api_paste_config = /etc/nova/api-paste.ini\n\
[spice]\n\
enabled = true\n\
html5proxy_base_url = http://$controllerIP:6082/spice_auto.html\n\
html5proxy_host = \$my_ip\n\
html5proxy_port = 6082\n\
keymap = en-us\n\
server_listen = 0.0.0.0\n\
server_proxyclient_address = \$my_ip\n\
agent_enabled = true\n\
[vnc]\n\
enabled = false" > /etc/nova/nova.conf && \
  chmod 640 /etc/nova/nova.conf && \
  chgrp nova /etc/nova/nova.conf && \
  cat hosts >>/etc/hosts && \
  rm -f docker-build.sh  Dockerfile.nova  sources.list && \
  apt autoremove && \
  apt-get clean && \
  rm -rf /usr/share/man /usr/share/doc && \
  rm -rf /var/lib/apt/lists/* && \
  du -sh /* ; \
  du -sh /usr/*; \
  cat /etc/hosts
CMD ["/bin/bash","./start.sh"]
